# Generated by Django 4.1.1 on 2022-10-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_like_alter_profile_profile_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like',
            new_name='LikePost',
        ),
    ]
